#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: string get_title();

# Short bio or description (displayed in the header)
description: Adventures in C++ing

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/avatar.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: bewuethr
  instagram: 
  linkedin: bewuethr
  pinterest: 
  rss: dummy
  twitter: bewuethr
  stackoverflow: users/3266847/benjamin
  youtube:

# Your disqus shortname, entering this will enable commenting on posts
disqus: stringgettitle

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-507261-6

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://bewuethr.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# prose
prose:
  media: 'images'

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
